package auditlog

// ChangeKey represents an audit log change key.
// See https://discord.com/developers/docs/resources/audit-log#audit-log-change-object-audit-log-change-key.
type ChangeKey string

const (
	AfkChannelID                ChangeKey = "afk_channel_id"
	AfkTimeout                  ChangeKey = "afk_timeout"
	Allow                       ChangeKey = "allow"
	ApplicationID               ChangeKey = "application_id"
	Archived                    ChangeKey = "archived"
	Asset                       ChangeKey = "asset"
	AutoArchiveDuration         ChangeKey = "auto_archive_duration"
	Available                   ChangeKey = "available"
	AvatarHash                  ChangeKey = "avatar_hash"
	BannerHash                  ChangeKey = "banner_hash"
	Bitrate                     ChangeKey = "bitrate"
	ChannelID                   ChangeKey = "channel_id"
	Code                        ChangeKey = "code"
	Color                       ChangeKey = "color"
	Deaf                        ChangeKey = "deaf"
	DefaultAutoArchiveDuration  ChangeKey = "default_auto_archive_duration"
	DefaultMessageNotifications ChangeKey = "default_message_notifications"
	Deny                        ChangeKey = "deny"
	Description                 ChangeKey = "description"
	DiscoverySplashHash         ChangeKey = "discovery_splash_hash"
	EnableEmoticons             ChangeKey = "enable_emoticons"
	ExpireBehavior              ChangeKey = "expire_behavior"
	ExpireGracePeriod           ChangeKey = "expire_grace_period"
	ExplicitContentFilter       ChangeKey = "explicit_content_filter"
	FormatType                  ChangeKey = "format_type"
	GuildID                     ChangeKey = "guild_id"
	Hoist                       ChangeKey = "hoist"
	IconHash                    ChangeKey = "icon_hash"
	ID                          ChangeKey = "id"
	InviterID                   ChangeKey = "inviter_id"
	Locked                      ChangeKey = "locked"
	MaxAge                      ChangeKey = "max_age"
	MaxUses                     ChangeKey = "max_uses"
	Mentionable                 ChangeKey = "mentionable"
	MfaLevel                    ChangeKey = "mfa_level"
	Mute                        ChangeKey = "mute"
	Name                        ChangeKey = "name"
	Nick                        ChangeKey = "nick"
	Nsfw                        ChangeKey = "nsfw"
	OwnerID                     ChangeKey = "owner_id"
	PermissionOverwrites        ChangeKey = "permission_overwrites"
	Permissions                 ChangeKey = "permissions"
	Position                    ChangeKey = "position"
	PreferredLocale             ChangeKey = "preferred_locale"
	PrivacyLevel                ChangeKey = "privacy_level"
	PruneDeleteDays             ChangeKey = "prune_delete_days"
	PublicUpdatesChannelID      ChangeKey = "public_updates_channel_id"
	RateLimitPerUser            ChangeKey = "rate_limit_per_user"
	Region                      ChangeKey = "region"
	RulesChannelID              ChangeKey = "rules_channel_id"
	SplashHash                  ChangeKey = "splash_hash"
	SystemChannelID             ChangeKey = "system_channel_id"
	Tags                        ChangeKey = "tags"
	Temporary                   ChangeKey = "temporary"
	Topic                       ChangeKey = "topic"
	Type                        ChangeKey = "type"
	UnicodeEmoji                ChangeKey = "unicode_emoji"
	UserLimit                   ChangeKey = "user_limit"
	Uses                        ChangeKey = "uses"
	VanityUrlCode               ChangeKey = "vanity_url_code"
	VerificationLevel           ChangeKey = "verification_level"
	WidgetChannelID             ChangeKey = "widget_channel_id"
	WidgetEnabled               ChangeKey = "widget_enabled"
	Add                         ChangeKey = "add"
	Remove                      ChangeKey = "remove"
)
